services:
  # nginx:
  #   image: nginx:stable-alpine
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - './nginx.conf:/etc/nginx/nginx.conf'
  #     - '/etc/letsencrypt:/etc/letsencrypt'
  #   depends_on:
  #     - app
  #   networks:
  #     - main
  app:
    build: .
    env_file:
      - .env.prod
      - .env
    ports:
      - '8000:8000'
    networks:
        - main

# networks:
#   main:
#     driver: bridge
