services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
      - '/etc/letsencrypt:/etc/letsencrypt'
    depends_on:
      - app
    networks:
      - main
  broker_redis:
    image: redis:latest
    ports:
      - "6380:6379"
    volumes:
      - ./broker-redis-data:/broker-data

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 10s
      retries: 5
    restart: always
    networks:
      - main

  app:
    build: .
    env_file:
      - .env.prod
      - .env
    ports:
      - '8000:8000'
    networks:
      - main
  celery_worker:
    build: .
    env_file: .env
    command: celery -A app.celery_app worker --loglevel=info --pool=solo
    depends_on:
      - broker_redis
      - app
    volumes:
      - .:/app
    networks:
      - main

  celery_beat:
    build: .
    env_file: .env
    command: celery -A app.celery_app beat --loglevel=info
    depends_on:
      - broker_redis
      - app
    volumes:
      - .:/app

    networks:
      - main
volumes:
  broker-redis-data:

networks:
  main:
    external: true

