services:
  app:
    build: .
    env_file:
      - .env.prod
      - .env.test
      - .env
    ports:
      - '8000:8000'
    depends_on:
      postgres:
        condition: service_healthy
      # redis:
      #     condition: service_healthy
    networks:
        - main

  postgres:
    image: postgres:13-alpine
    env_file:
      - .env.prod
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -d default_db -U gen_user']
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - main
    ports:
      - '5433:5432'


volumes:
  postgres_data:

networks:
  main:
    driver: bridge
